import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import LogoutButton from "@/app/components/LogoutButton";
import UserSearch from "@/app/components/UserSearch";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="grid grid-cols-3 items-start gap-4 p-4">
          <div />
          <div className="flex justify-center">
            <UserSearch />
          </div>
          {user ? (
            <div className="flex flex-col items-end gap-1 justify-self-end">
              <Link href={`/profile/${user.id}`} className="cursor-pointer">
                {user.email}
              </Link>
              <LogoutButton />
            </div>
          ) : (
            <Link href="/signup" className="cursor-pointer justify-self-end">
              Sign up
            </Link>
          )}
        </header>
        {user && (
          <nav className="flex justify-center gap-6 border-b border-neutral-200 py-3 dark:border-neutral-800">
            <Link href="/explore" className="cursor-pointer">
              Explore
            </Link>
            <Link href="/projects" className="cursor-pointer">
              My projects
            </Link>
            <Link href="/applications" className="cursor-pointer">
              My applications
            </Link>
            <Link href="/messages" className="cursor-pointer">
              Messages
            </Link>
            <Link href="/notifications" className="cursor-pointer">
              Notifications
            </Link>
          </nav>
        )}
        {children}
      </body>
    </html>
  );
}
